# Generated by Django 4.2.5 on 2023-10-04 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listingbid_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='UserComment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
