# Generated by Django 4.2.5 on 2023-10-04 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_allowedit_listing_startbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingbid',
            name='listing',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ListingBid', to='auctions.listing'),
            preserve_default=False,
        ),
    ]
